language: csharp
solution: ActivoutRestClient.sln
mono: none
dotnet: 2.2.203
dist: xenial
install:
  - dotnet tool install --global dotnet-sonarscanner
script:
  - dotnet build ./Activout.RestClient/
  - dotnet test --no-build ./Activout.RestClient.Test/ --verbosity=diag
  - $HOME/.dotnet/tools/dotnet-sonarscanner begin /k:"Activout.RestClient" /o:"activout" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_TOKEN" /version:"$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT"
  - dotnet build
  - $HOME/.dotnet/tools/dotnet-sonarscanner end /d:sonar.login="$SONAR_TOKEN"
cache:
  directories:
    - $HOME/.nuget
    - $HOME/.sonar/cache
    - /usr/share/dotnet/sdk/NuGetFallbackFolder
